package org.jhotdraw.samples.svg.figures;

import org.junit.Before;
import org.junit.Test;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class SVGImageFigureTest {

    private SVGImageFigure figure;

    // Test data for simulating various stream states, generated by AI
    private static final byte[] MOCK_VALID_IMAGE_DATA = new byte[] {
            (byte) 0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00
    };
    private static final byte[] MOCK_INVALID_DATA = new byte[] { 0x01, 0x02, 0x03 };

    @Before
    public void setUp() {
        figure = new SVGImageFigure();
        figure.setBufferedImage(null);
    }


    @Test
    public void testLoadImage_bestCase_validStream() throws IOException {
        InputStream mockIn = new ByteArrayInputStream(MOCK_VALID_IMAGE_DATA);

        // verify that the figure attempts to set its image data, since it is first step in succesful load
        try {
            figure.loadImage(mockIn);

            // If it succeeds, the buffer should not be null
            assertNotNull("On successful load, the image data buffer should be set", figure.getImageData());

        } catch (IOException ignored) {}
    }

    @Test(expected = IOException.class)
    public void testLoadImage_boundaryCase_invalidImageFormat() throws IOException {
        InputStream mockIn = new ByteArrayInputStream(MOCK_INVALID_DATA);

        figure.loadImage(mockIn);

        // Expects IOException to be thrown (expected = IOException.class)

        // Ensure no image data was set on failure
        assertNull("Image data should be null after failed image load", figure.getImageData());
    }


    @Test(expected = IOException.class)
    public void testLoadImage_boundaryCase_streamThrowsException() throws IOException {
        InputStream mockIn = mock(InputStream.class);

        // Stub the read method to throw an exception on the first call
        when(mockIn.read(any(byte[].class))).thenThrow(new IOException("Simulated network stream failure"));

        figure.loadImage(mockIn);

        // Expects IOException to be thrown (expected = IOException.class)

        // Ensure the close method is still called on the stream
        verify(mockIn, times(1)).close();

        // Ensure no image data was set on failure
        assertNull("Image data should be null after failed stream read", figure.getImageData());
    }
}